name: Build ZMK firmware
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      amend_commit: false
      install_branch: "main"
      keymap_patterns: "config/cornix.keymap"
      json_path: "config/cornix.json"
      config_path: "keymap-drawer/config.yaml" # config file, ignored if not exists
      output_folder: "image"
      destination: "both"
      parse_args: "" # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: "cornix:'--dts-layout keymap-drawer/cornix-layouts.dtsi'"
      # draw_args: ""
      debug_mode: true
  create_png:
    runs-on: ubuntu-latest
    needs:
      - draw
    steps:
      - name: Install PNG Image Tools
        run: |
          sudo apt-get update
          sudo apt-get install -qq -y imagemagick
          sudo apt-get install -qq -y inkscape
          set -x
          which convert
          convert --version
      - uses: actions/checkout@v4
      - run: |
          git config --global user.email "linrongbin16@outlook.com"
          git config --global user.name "linrongbin16"
          git pull
      - name: Generate PNG
        run: |
          set -x
          # Use 5x times density for bigger PNG, by default is 96
          convert -density 480 ./image/cornix.svg ./image/cornix.png
          git status
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(png): auto-create png image"
          file_pattern: "image/cornix.png"
